default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: dev
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: api-teste-james

test:
  <<: *default
  database: api-teste-james-rspec